name: Build and Deploy to Cloud Run

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create api .env file
        run: |
          touch packages/api/.env
          echo "${{ secrets.ENV_API }}" >> packages/api/.env

      - name: Create app .env file
        run: |
          touch packages/app/.env
          echo "${{ secrets.ENV_APP }}" >> packages/app/.env

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Docker Build
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cheese-api:latest .

      - name: Docker Push
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cheese-api:latest

      - name: Deploy
        run: |
          gcloud run deploy cheese-api \
          --port 8080 \
          --region asia-east1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cheese-api:latest \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
